PCA TEST

In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [104]:
df = pd.read_csv(r'C:\Users\amitd\OneDrive\Documents\GitHub\AI_LEARNINGS\Principal Component Analysis\raw_merged_heart_dataset.csv', na_values=["?"])
df = df.replace("?", None)
#df = df.round().astype(int)
#df.to_csv(r'C:\Users\amitd\OneDrive\Documents\GitHub\AI_LEARNINGS\Principal Component Analysis\converted_heart_dataset.csv', index=False)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,1.0,1
1,37,1,2,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,2.0,1
2,41,0,1,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,2.0,1
3,56,1,1,120.0,236.0,0.0,1.0,178.0,0.0,0.8,2.0,0.0,2.0,1
4,57,0,0,120.0,354.0,0.0,1.0,163.0,1.0,0.6,2.0,0.0,2.0,1

In [105]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
2176,60,1,0,140.0,207.0,0.0,0.0,138.0,1.0,1.9,2.0,1.0,3.0,0
2177,46,1,0,140.0,311.0,0.0,1.0,120.0,1.0,1.8,1.0,2.0,3.0,0
2178,59,1,3,134.0,204.0,0.0,1.0,162.0,0.0,0.8,2.0,2.0,2.0,0
2179,54,1,1,154.0,232.0,0.0,0.0,164.0,0.0,0.0,2.0,1.0,2.0,0
2180,53,1,0,110.0,335.0,0.0,1.0,143.0,1.0,3.0,1.0,1.0,3.0,0

In [106]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
count,2181.000000,2181.000000,2181.000000,2180.000000,2158.000000,2173.000000,2180.000000,2180.000000,2180.000000,2181.000000,1991.000000,1890.000000,1915.000000,2181.000000
mean,53.477762,0.693260,1.248968,131.679817,247.366543,0.138058,0.546789,148.064220,0.327523,0.990509,1.446007,0.730688,2.703916,0.496103
std,9.194787,0.461246,1.123520,17.565488,53.894818,0.345040,0.631231,23.326238,0.469417,1.141851,0.617153,1.015476,1.302100,0.500099
min,28.000000,0.000000,0.000000,92.000000,85.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,46.000000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,54.000000,1.000000,1.000000,130.000000,242.000000,0.000000,0.000000,151.000000,0.000000,0.600000,1.000000,0.000000,2.000000,0.000000
75%,60.000000,1.000000,2.000000,140.000000,277.000000,0.000000,1.000000,165.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000,7.000000,1.000000

In [107]:
df.shape

(2181, 14)

In [108]:
df[30:40]

,age,sex,cp,trestbps,chol,fbs,restecg,thalachh,exang,oldpeak,slope,ca,thal,target
30,41,0,1,105.0,198.0,0.0,1.0,168.0,0.0,0.0,2.0,1.0,2.0,1
31,65,1,0,120.0,177.0,0.0,1.0,140.0,0.0,0.4,2.0,0.0,3.0,1
32,44,1,1,130.0,219.0,0.0,0.0,188.0,0.0,0.0,2.0,0.0,2.0,1
33,54,1,2,125.0,273.0,0.0,0.0,152.0,0.0,0.5,0.0,1.0,2.0,1
34,51,1,3,125.0,213.0,0.0,0.0,125.0,1.0,1.4,2.0,1.0,2.0,1
35,46,0,2,142.0,177.0,0.0,0.0,160.0,1.0,1.4,0.0,0.0,2.0,1
36,54,0,2,135.0,304.0,1.0,1.0,170.0,0.0,0.0,2.0,0.0,2.0,1
37,54,1,2,150.0,232.0,0.0,0.0,165.0,0.0,1.6,2.0,0.0,3.0,1
38,65,0,2,155.0,269.0,0.0,1.0,148.0,0.0,0.8,2.0,0.0,2.0,1
39,65,0,2,160.0,360.0,0.0,0.0,151.0,0.0,0.8,2.0,0.0,2.0,1

In [109]:
df.isna().sum()

age           0
sex           0
cp            0
trestbps      1
chol         23
fbs           8
restecg       1
thalachh      1
exang         1
oldpeak       0
slope       190
ca          291
thal        266
target        0
dtype: int64

In [110]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      1
chol         23
fbs           8
restecg       1
thalachh      1
exang         1
oldpeak       0
slope       190
ca          291
thal        266
target        0
dtype: int64

In [111]:
df = df.fillna(0).astype(int)

In [112]:
X = df.drop('target', axis=1)
y = df['target']

In [113]:
sc = StandardScaler()
X_scaled = sc.fit_transform(X)
X_scaled

array([[ 1.03585008,  0.66517691,  1.55887966, ..., -1.84155941,
        -0.64798871, -0.9118803 ],
       [-1.79248749,  0.66517691,  0.6686161 , ..., -1.84155941,
        -0.64798871, -0.24827972],
       [-1.35735863, -1.50335947, -0.22164746, ...,  0.94860458,
        -0.64798871, -0.24827972],
       ...,
       [ 0.60072122,  0.66517691,  1.55887966, ...,  0.94860458,
         1.39873594, -0.24827972],
       [ 0.05681015,  0.66517691, -0.22164746, ...,  0.94860458,
         0.37537362, -0.24827972],
       [-0.05197206,  0.66517691, -1.11191102, ..., -0.44647741,
         0.37537362,  0.41532086]], shape=(2181, 13))

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [115]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7688787185354691

In [116]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(X_pca.shape, X_pca)

(2181, 2) [[-11.00236535  -0.84885258]
 [  4.20232522  41.14034925]
 [-41.44017926  24.90635232]
 ...
 [-40.61630605  11.95638903]
 [-12.12722253  13.58423357]
 [ 89.42321284  -1.35744885]]

In [117]:
pca.explained_variance_ratio_

array([0.78675728, 0.12662057])

In [118]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

In [119]:
model1 = LogisticRegression()
model1.fit(X_train_pca, y_train)
model1.score(X_test_pca, y_test)

0.620137299771167