Outlier Percentile Housing Data

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r"C:\Users\amitd\OneDrive\Documents\GitHub\AI_LEARNINGS\Outlier_Percentile\housing_cleaned.csv")
df.head()

        price  bhk  area_sqft  parking
0   9500000.0  3.0     1400.0      0.0
1  57500000.0  3.0     1400.0      0.0
2   4000000.0  3.0     1400.0      0.0
3  13800000.0  4.0     1400.0      0.0
4  11000000.0  4.0     1400.0      0.0

In [16]:
df.shape

(12000, 4)

In [17]:
df.describe()

              price           bhk      area_sqft       parking
count  1.200000e+04  12000.000000   12000.000000  12000.000000
mean   3.153475e+07      3.089917    1640.961417      0.691583
std    5.002292e+07      0.932597    2229.662233      0.461859
min    7.500000e+05      1.000000      32.000000      0.000000
25%    7.700000e+06      3.000000     900.000000      0.000000
50%    1.865000e+07      3.000000    1400.000000      1.000000
75%    3.470000e+07      4.000000    1900.000000      1.000000
max    1.500000e+09     12.000000  109000.000000      1.000000

In [18]:
df1 = df[['price','area_sqft']]
df1.head()

        price  area_sqft
0   9500000.0     1400.0
1  57500000.0     1400.0
2   4000000.0     1400.0
3  13800000.0     1400.0
4  11000000.0     1400.0

In [19]:
max_threshold = df1['area_sqft'].quantile(0.95)
max_threshold

np.float64(3500.0)

In [20]:
min_threshold = df1['area_sqft'].quantile(0.05)
min_threshold

np.float64(521.9000000000001)

In [21]:
df1[(df1['area_sqft']<max_threshold) & (df1['area_sqft']>min_threshold)]

            price  area_sqft
0       9500000.0     1400.0
1      57500000.0     1400.0
2       4000000.0     1400.0
3      13800000.0     1400.0
4      11000000.0     1400.0
...           ...        ...
11995   5000000.0      630.0
11996  60000000.0     1800.0
11997   4500000.0     1200.0
11998   3250000.0      650.0
11999   3300000.0      650.0

[10787 rows x 2 columns]