Outlier Detection

In [37]:
import pandas as pd
import numpy as np
import matplotlib_inline as pyplot
%matplotlib inline
import seaborn as sns

In [38]:
df = pd.read_csv(r"C:\Users\amitd\OneDrive\Documents\GitHub\AI_LEARNINGS\Outlier_Percentile\creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [39]:
df.shape

(284807, 31)

In [40]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [41]:
df1 = df[['Time','Amount']]
df1.head()

   Time  Amount
0   0.0  149.62
1   0.0    2.69
2   1.0  378.66
3   1.0  123.50
4   2.0   69.99

In [42]:
df1.shape

(284807, 2)

In [43]:
df1.describe()

                Time         Amount
count  284807.000000  284807.000000
mean    94813.859575      88.349619
std     47488.145955     250.120109
min         0.000000       0.000000
25%     54201.500000       5.600000
50%     84692.000000      22.000000
75%    139320.500000      77.165000
max    172792.000000   25691.160000

In [44]:
max_threshold = df1['Amount'].quantile(0.99)
max_threshold

np.float64(1017.9700000000012)

In [45]:
min_threshold = df1['Amount'].quantile(0.01)
min_threshold

np.float64(0.12)

In [46]:
df1[df1['Amount']>max_threshold]

            Time    Amount
51          36.0   1402.95
89          59.0   1142.02
164        103.0   3828.04
865        656.0   1602.99
1027       775.0   1528.90
...          ...       ...
283875  171943.0   1026.46
284154  172199.0   1088.04
284249  172273.0  10199.44
284383  172397.0   1114.00
284497  172498.0   1484.66

[2849 rows x 2 columns]

In [47]:
df1[df1['Amount']<min_threshold]

            Time  Amount
383        282.0    0.00
514        380.0    0.00
533        402.0    0.01
534        403.0    0.00
541        406.0    0.00
...          ...     ...
284125  172176.0    0.05
284598  172589.0    0.01
284641  172632.0    0.01
284672  172665.0    0.01
284770  172759.0    0.00

[2769 rows x 2 columns]

In [53]:
df2 = df1[(df1['Amount']<max_threshold) & (df1['Amount']>min_threshold)]
df2.head()

   Time  Amount
0   0.0  149.62
1   0.0    2.69
2   1.0  378.66
3   1.0  123.50
4   2.0   69.99

In [54]:
df2.shape

(278955, 2)

In [55]:
df2.describe()

                Time         Amount
count  278955.000000  278955.000000
mean    94894.249445      71.477515
std     47481.453838     129.525977
min         0.000000       0.130000
25%     54301.500000       5.990000
50%     84729.000000      22.000000
75%    139398.000000      75.160000
max    172792.000000    1017.500000